/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package bma.siteone.alarmclient.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TAlarmClient {

  public interface Iface {

    public void commitAlarm(TAlarmCommitForm alarmCommitForm) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void commitAlarm(TAlarmCommitForm alarmCommitForm, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.commitAlarm_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public void commitAlarm(TAlarmCommitForm alarmCommitForm) throws org.apache.thrift.TException
    {
      send_commitAlarm(alarmCommitForm);
    }

    public void send_commitAlarm(TAlarmCommitForm alarmCommitForm) throws org.apache.thrift.TException
    {
      commitAlarm_args args = new commitAlarm_args();
      args.setAlarmCommitForm(alarmCommitForm);
      sendBase("commitAlarm", args);
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void commitAlarm(TAlarmCommitForm alarmCommitForm, org.apache.thrift.async.AsyncMethodCallback<commitAlarm_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      commitAlarm_call method_call = new commitAlarm_call(alarmCommitForm, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class commitAlarm_call extends org.apache.thrift.async.TAsyncMethodCall {
      private TAlarmCommitForm alarmCommitForm;
      public commitAlarm_call(TAlarmCommitForm alarmCommitForm, org.apache.thrift.async.AsyncMethodCallback<commitAlarm_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, true);
        this.alarmCommitForm = alarmCommitForm;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("commitAlarm", org.apache.thrift.protocol.TMessageType.CALL, 0));
        commitAlarm_args args = new commitAlarm_args();
        args.setAlarmCommitForm(alarmCommitForm);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("commitAlarm", new commitAlarm());
      return processMap;
    }

    private static class commitAlarm<I extends Iface> extends org.apache.thrift.ProcessFunction<I, commitAlarm_args> {
      public commitAlarm() {
        super("commitAlarm");
      }

      protected commitAlarm_args getEmptyArgsInstance() {
        return new commitAlarm_args();
      }

      protected org.apache.thrift.TBase getResult(I iface, commitAlarm_args args) throws org.apache.thrift.TException {
        iface.commitAlarm(args.alarmCommitForm);
        return null;
      }
    }

  }

  public static class commitAlarm_args implements org.apache.thrift.TBase<commitAlarm_args, commitAlarm_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("commitAlarm_args");

    private static final org.apache.thrift.protocol.TField ALARM_COMMIT_FORM_FIELD_DESC = new org.apache.thrift.protocol.TField("alarmCommitForm", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new commitAlarm_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new commitAlarm_argsTupleSchemeFactory());
    }

    public TAlarmCommitForm alarmCommitForm; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      ALARM_COMMIT_FORM((short)1, "alarmCommitForm");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // ALARM_COMMIT_FORM
            return ALARM_COMMIT_FORM;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.ALARM_COMMIT_FORM, new org.apache.thrift.meta_data.FieldMetaData("alarmCommitForm", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TAlarmCommitForm.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(commitAlarm_args.class, metaDataMap);
    }

    public commitAlarm_args() {
    }

    public commitAlarm_args(
      TAlarmCommitForm alarmCommitForm)
    {
      this();
      this.alarmCommitForm = alarmCommitForm;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public commitAlarm_args(commitAlarm_args other) {
      if (other.isSetAlarmCommitForm()) {
        this.alarmCommitForm = new TAlarmCommitForm(other.alarmCommitForm);
      }
    }

    public commitAlarm_args deepCopy() {
      return new commitAlarm_args(this);
    }

    @Override
    public void clear() {
      this.alarmCommitForm = null;
    }

    public TAlarmCommitForm getAlarmCommitForm() {
      return this.alarmCommitForm;
    }

    public commitAlarm_args setAlarmCommitForm(TAlarmCommitForm alarmCommitForm) {
      this.alarmCommitForm = alarmCommitForm;
      return this;
    }

    public void unsetAlarmCommitForm() {
      this.alarmCommitForm = null;
    }

    /** Returns true if field alarmCommitForm is set (has been assigned a value) and false otherwise */
    public boolean isSetAlarmCommitForm() {
      return this.alarmCommitForm != null;
    }

    public void setAlarmCommitFormIsSet(boolean value) {
      if (!value) {
        this.alarmCommitForm = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case ALARM_COMMIT_FORM:
        if (value == null) {
          unsetAlarmCommitForm();
        } else {
          setAlarmCommitForm((TAlarmCommitForm)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case ALARM_COMMIT_FORM:
        return getAlarmCommitForm();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case ALARM_COMMIT_FORM:
        return isSetAlarmCommitForm();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof commitAlarm_args)
        return this.equals((commitAlarm_args)that);
      return false;
    }

    public boolean equals(commitAlarm_args that) {
      if (that == null)
        return false;

      boolean this_present_alarmCommitForm = true && this.isSetAlarmCommitForm();
      boolean that_present_alarmCommitForm = true && that.isSetAlarmCommitForm();
      if (this_present_alarmCommitForm || that_present_alarmCommitForm) {
        if (!(this_present_alarmCommitForm && that_present_alarmCommitForm))
          return false;
        if (!this.alarmCommitForm.equals(that.alarmCommitForm))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(commitAlarm_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      commitAlarm_args typedOther = (commitAlarm_args)other;

      lastComparison = Boolean.valueOf(isSetAlarmCommitForm()).compareTo(typedOther.isSetAlarmCommitForm());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAlarmCommitForm()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alarmCommitForm, typedOther.alarmCommitForm);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("commitAlarm_args(");
      boolean first = true;

      sb.append("alarmCommitForm:");
      if (this.alarmCommitForm == null) {
        sb.append("null");
      } else {
        sb.append(this.alarmCommitForm);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class commitAlarm_argsStandardSchemeFactory implements SchemeFactory {
      public commitAlarm_argsStandardScheme getScheme() {
        return new commitAlarm_argsStandardScheme();
      }
    }

    private static class commitAlarm_argsStandardScheme extends StandardScheme<commitAlarm_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, commitAlarm_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // ALARM_COMMIT_FORM
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.alarmCommitForm = new TAlarmCommitForm();
                struct.alarmCommitForm.read(iprot);
                struct.setAlarmCommitFormIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, commitAlarm_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.alarmCommitForm != null) {
          oprot.writeFieldBegin(ALARM_COMMIT_FORM_FIELD_DESC);
          struct.alarmCommitForm.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class commitAlarm_argsTupleSchemeFactory implements SchemeFactory {
      public commitAlarm_argsTupleScheme getScheme() {
        return new commitAlarm_argsTupleScheme();
      }
    }

    private static class commitAlarm_argsTupleScheme extends TupleScheme<commitAlarm_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, commitAlarm_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetAlarmCommitForm()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetAlarmCommitForm()) {
          struct.alarmCommitForm.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, commitAlarm_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.alarmCommitForm = new TAlarmCommitForm();
          struct.alarmCommitForm.read(iprot);
          struct.setAlarmCommitFormIsSet(true);
        }
      }
    }

  }

}
